### ISSUE TITLE
支持根据输入的关键字动态获取吗？

### ISSUE THREAD

**Issue by chanyipiaomiao** [TerryZ/v-suggest#10]
支持根据输入的关键字动态获取吗？

**Comment by TerryZ** [comment]
动态获取什么？

**Comment by chanyipiaomiao** [comment]
动态获取 suggest列表，就是输入关键字就立即调用接口获取该关键字对应的suggest列表

**Comment by TerryZ** [comment]
插件的使用是要求默认提供一个数据列表，在输入框中输入的内容限定在该列表范围内，后期会增加服务端数据源模式
