### ISSUE TITLE
how can I make dropdown to be open by just clicking in the input

### ISSUE THREAD

**Issue by moustafaart4muslim** [TerryZ/v-suggest#11]
Hi,

I want to make the dropdown to be open by just clicking inside the input, before typing text..
I mean to be open viewing all the items in the list

How to achieve this?

**Comment by TerryZ** [comment]
What do you want to display in the dropdown, the full result list?

**Comment by moustafaart4muslim** [comment]
yes, the full result list.

**Comment by moustafaart4muslim** [comment]
@TerryZ  Reminder.

**Comment by TerryZ** [comment]
For currently version v-suggestion, only enter some text in the input element and the suggestion items showup, no way to show all the items in the list.

**Comment by TerryZ** [comment]
Ok, i will think about it.

**Comment by moustafaart4muslim** [comment]
Thank you.

**Comment by TerryZ** [comment]
Added `full-list` prop in `v2.1.0` version, it set to config display full list when input element get focus

**Comment by moustafaart4muslim** [comment]
Thank you very much. 
Worked great.👍

But having small issue, When you focus in the input, it's working fine, start typing, filter works file, Now clear what you have typed, it should  show the full list again when the input becomes clear, but it doesn't. To be able to show the full list again after start typing and then clearing the input, I  have to click by the mouse outside the input then re-click inside it.

Again, thanks a lot.

**Comment by TerryZ** [comment]
Issue fixed on last release ( 2.2.0 ).

**Comment by moustafaart4muslim** [comment]
Sorry, It still shows the same behavior.
When you focus in the input, it's working fine, start typing, filter works file, Now clear what you have typed, it should show the full list again when the input becomes clear, but it doesn't. To be able to show the full list again after start typing and then clearing the input, I have to click by the mouse outside the input then re-click inside it.

**Comment by moustafaart4muslim** [comment]
Sorry, It still shows the same behavior.
When you focus in the input, it's working fine, start typing, filter works file, Now clear what you have typed, it should show the full list again when the input becomes clear, but it doesn't. To be able to show the full list again after start typing and then clearing the input, I have to click by the mouse outside the input then re-click inside it.
@TerryZ
