### ISSUE TITLE
Emit "Clear" event - when user clicks on "Clear" button

### ISSUE THREAD

**Issue by tikvarova** [TerryZ/v-suggest#13]
Dear Terry,

Could you please emit this event! It will be very useful to catch it and do some additional work in a complex component For example if we have some list of items in a table/ul/ol and we want to dynamically clear list of items if we clear our v-suggest component!

Thanks in advance

**Comment by TerryZ** [comment]
OK and stay tuned.

**Comment by tikvarova** [comment]
Thanks man! That's cool!

**Comment by TerryZ** [comment]
Added `clear` event on the last release.
