### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by cpfarher** [TerryZ/v-suggest#8]
There is a bug on line https://github.com/TerryZ/v-suggest/blob/master/src/Suggest.vue#L168, I think you must check for undefined values...

**Comment by cpfarher** [comment]
@TerryZ my error!
I realized that the problem is when you pass a show-field that doesn't exist on the data list... I pass descripcion instead of description....
Anyway, maybe you need to keep present this type of errors and alert with a warning? and catch the exception?

**Comment by TerryZ** [comment]
1. When null, undefined or some abnormal situation else will parse to '' (empty string).
2. When you pass wrong field name, i think throw that error in console will be better
